settings:
  permission: "ggwave.use"
ggwave-messages:
  - "&a&lGG"
  - "&b&lGG"
  - "&c&lGG"
  - "&d&lGG"
  - "&e&lGG"
  - "&f&lGG"
messages:
  WAVE-START:
    - "&f&m--&e&lG&6&lG &e&lW&6&lA&e&lV&6&lE &e&lA&6&lC&e&lT&6&lI&e&lV&6&lA&e&lT&6&lE&e&lD&f&m--"
  WAVE-END:
    - "&f&m--&e&lTHE G&e&lG &e&lW&6&lA&e&lV&6&lE &e&lHAS ENDED!&f&m--"
  WAVE-ONGOING: "&a&l(!) &aYou cannot start a wave as there is already one ongoing!"
  WAVE-NOT-ONGOING: "&c&l(!) &cYou cannot end a wave as there is not one ongoing!"
  INVALID-DURATION: "&c&l(!) &cYou must specify a valid duration to start a GGWave!"
  NO-PERMISSION: "&c&l(!) &cYou do not have permission to execute that command!"